'''
Autor: André Guido.
'''
import os
# Declaración de campos/parámetros y listas a utilizar en los ficheros.
campos = ["tituloVideo.txt", "nombreAutorVideo.txt", "categoriaVideo.txt", "descripcionVideo.txt", "lenguajeProgVideo.txt", "linkVideo.txt", "nombreColabVideo.txt","motivoCambioVideo.txt"]
if all(os.path.exists(c) for c in campos):
    with open(campos[0], "r") as f: tituloVideo=f.read().splitlines()
    with open(campos[1], "r") as f: nombreAutorVideo=f.read().splitlines()
    with open(campos[2], "r") as f: categoriaVideo=f.read().splitlines()
    with open(campos[3], "r") as f: descripcionVideo=f.read().splitlines()
    with open(campos[4], "r") as f: lenguajeProgVideo=f.read().splitlines()
    with open(campos[5], "r") as f: linkVideo=f.read().splitlines()
    with open(campos[6], "r") as f: nombreColabVideo=f.read().splitlines()
    with open(campos[7], "r") as f: motivoCambioVideo=f.read().splitlines()
else:
    tituloVideo=[]
    nombreAutorVideo=[]
    categoriaVideo=[]
    descripcionVideo=[]
    lenguajeProgVideo=[]
    linkVideo=[]
    nombreColabVideo=[]
    motivoCambioVideo=[]

#Función para guardar los datos del video en un ficheros.
def guardarDatosVideo():
    with open(campos[0], "w") as f: f.write("\n".join(tituloVideo))
    with open(campos[1], "w") as f: f.write("\n".join(nombreAutorVideo))
    with open(campos[2], "w") as f: f.write("\n".join(categoriaVideo))
    with open(campos[3], "w") as f: f.write("\n".join(descripcionVideo))
    with open(campos[4], "w") as f: f.write("\n".join(lenguajeProgVideo))
    with open(campos[5], "w") as f: f.write("\n".join(linkVideo))
    with open(campos[6], "w") as f: f.write("\n".join(nombreColabVideo))
    with open(campos[7], "w") as f: f.write("\n".join(motivoCambioVideo))

#Función para agregar/registrar los datos de un video.
def registrarVideo():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("         FICHA TÉCNICA DE VIDEO          ")
    print("*****************************************")
    print(" Estimado usuario, muchas gracias por su ")
    print("interés en ampliar los recursos audiovisuales")
    print(" referentes a códigos de programación en ")
    print("CodeLanguageEs. Amablemente le solicitamos")
    print("que rellene la siguiente ficha técnica del")
    print("video que desea registrar en la plataforma.")
    print("*****************************************")
    while True:
        if len(tituloVideo) < 100:
            tituloVideo.append(input("Título del video: "))
            nombreAutorVideo.append(input("Autor: "))
            categoriaVideo.append(input("Categoría del video: "))
            descripcionVideo.append(input("Breve descripción del video: "))
            lenguajeProgVideo.append(input("Lenguaje de programación: "))
            linkVideo.append(input("Enlace de acceso al video: "))
            nombreColabVideo.append(input("Usuario que sube el archivo: "))
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("Usted está a punto de registrar un video ")
            print("      con los siguientes parámetros.     ")
            print("*****************************************")
            print(f"Título del video: {tituloVideo}")
            print(f"Autor: {nombreAutorVideo}")
            print(f"Categoría del video: {categoriaVideo}")
            print(f"Descripción del video: {descripcionVideo}")
            print(f"Lenguaje de programación: {lenguajeProgVideo}")
            print(f"Enlace de acceso al video: {linkVideo}")
            print(f"Usuario que sube el archivo: {nombreColabVideo}")
            print("*****************************************")
            valRespuesta=input("Por favor, ingrese S/N para confirmar su acción: ")
            if valRespuesta.upper() == "S":
                guardarDatosVideo()
                os.system("cls")
                print("Los datos han sido guardados con éxito.")
                break
            elif valRespuesta.upper() == "N":
                os.system("cls")
                print("El proceso ha sido cancelado.")
                break
            else: 
                print("Opción no válida.")
                break

#Función para modificar los parámetros de un video.
def modificarVideo():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("                 VIDEOS                  ")
    print("*****************************************")
    print("Lista de video: ")
    for i in tituloVideo:
        print(f"{i}\n")
    print("*****************************************") 
    tituloBuscado=input("Ingrese el título del video que desea modificar: ")
    os.system("cls")
    if tituloBuscado in tituloVideo:
        pos=tituloVideo.index(tituloBuscado)
        print("*****************************************")
        print("             CodeLanguagueES             ")
        print("*****************************************")
        print("   MODIFICACIÓN DE PARÁMETROS DE VIDEO   ")
        print("*****************************************")
        print("Por favor, indique el parámetro del video")
        print("          que desea modificar.           ")
        print("*****************************************")
        print("1- Título del video.")
        print("2- Autor.")
        print("3- Categoría del video.")
        print("4- Descripción del video.")
        print("5- Lenguaje de programación.")
        print("6- Enlace de acceso al video.")
        print("7- Colaborador.")
        print("8- Cancelar.")
        print("*****************************************")
        valOpcionMod=int(input("Opción: "))
        os.system("cls")
        # Modificación del título del video.
        if valOpcionMod==1:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Video: {tituloVideo}          ")
            print("*****************************************")
            print(" Por favor, escriba el nuevo título del  ")
            print("   video y el motivo de cambio de este   ")
            print("               parámetro.                ")
            print("*****************************************")
            tituloVideo[pos]=input("Nuevo título: ")
            motivoCambioVideo.append(input("Motivo: "))
            guardarDatosVideo()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El título del video ha sido cambiado con ")
            print("éxito. Dentro de los próximos minutos los")
            print("  cambios serán visibles para todos los  ")
            print("                usuarios.                ")
            print("*****************************************")
        
        # Modificación del nombre del autor del video.
        elif valOpcionMod==2:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Video: {tituloVideo}          ")
            print("*****************************************")
            print("Por favor, escriba el nuevo autor del video")
            print("y el motivo de cambio de este parámetro.")
            print("*****************************************")
            nombreAutorVideo[pos]=input("Nuevo autor: ")
            motivoCambioVideo.append(input("Motivo: "))
            guardarDatosVideo()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El nombre del autor ha sido cambiado con ")
            print("éxito. Dentro de los próximos minutos los")
            print("  cambios serán visibles para todos los  ")
            print("                usuarios.                ")
            print("*****************************************")
        
        # Modificación de la categoría del video.
        elif valOpcionMod==3:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Video: {tituloVideo}          ")
            print("*****************************************")
            print("Por favor, escriba la nueva categoría del")
            print("video y el motivo de cambio de este parámetro.")
            print("*****************************************")
            categoriaVideo[pos]=input("Nueva categoría: ")
            motivoCambioVideo.append(input("Motivo: "))
            guardarDatosVideo()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("La categoría del video ha sido cambiada con")
            print("éxito. Dentro de los próximos minutos los")
            print("  cambios serán visibles para todos los  ")
            print("                usuarios.                ")
            print("*****************************************")
        
        #Modificaión de la descripción del video.
        elif valOpcionMod==4:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Video: {tituloVideo}          ")
            print("*****************************************")
            print(" Por favor, escriba la nueva descripción ")
            print(" del video y el motivo de cambio de este ")
            print("                parámetro.               ")
            print("*****************************************")
            descripcionVideo[pos]=input("Nueva descripción: ")
            motivoCambioVideo.append(input("Motivo: "))
            guardarDatosVideo()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("La descripción del video ha sido cambiada")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")
        
        #Modificación del lenguaje de programación al que pertenece el video.
        elif valOpcionMod==5:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Video: {tituloVideo}          ")
            print("*****************************************")
            print(" Por favor, escriba el nuevo lenguaje de ")
            print("programación del video y el motivo de cambio")
            print("            de este parámetro.           ")
            print("*****************************************")
            lenguajeProgVideo[pos]=input("Nuevo lenguaje de programación")
            motivoCambioVideo.append(input("Motivo: "))
            guardarDatosVideo()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El lenguaje de programación al que pertenecía")
            print("el video ha sido cambiado con éxtito. Dentro")
            print("de los próximos minutos los cambios serán")
            print("    visibles para todos los usuarios.    ")
            print("*****************************************")
        
        #Modificación del enlace de acceso al video.
        elif valOpcionMod==6:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Video: {tituloVideo}          ")
            print("*****************************************")
            print("Por favor, escriba el nuevo link de acceso")
            print(" al video y el motivo de cambio de este  ")
            print("               parámetro.                ")
            print("*****************************************")
            linkVideo[pos]=input("Nuevo link de acceso: ")
            motivoCambioVideo.append(input("Motivo: "))
            guardarDatosVideo()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El link de acceso al video ha sido cambiado")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")

        #Modificación del nombre del colaborador que subió el video.
        elif valOpcionMod==7:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Video: {tituloVideo}          ")
            print("*****************************************")
            print("  Por favor, escriba el nuevo nombre del ")
            print("colaborador y el motivo de cambio de este")
            print("               parámetro.                ")
            print("*****************************************")
            nombreColabVideo[pos]=input("Nuevo nombre de colaborador: ")
            motivoCambioVideo.append(input("Motivo: "))
            guardarDatosVideo()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El nombre del colaboradorha sido cambiado")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")
    
    elif valOpcionMod==8:
        print("Proceso cancelado.")
        return

#Función para eliminar un video del fichero.
def eliminarVideo():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("                 VIDEOS                  ")
    print("*****************************************")
    print("Lista de videos: ")
    for i in tituloVideo:
        print(f"{i}\n")
    print("*****************************************") 
    tituloBuscado=input("Ingrese el nombre del libro que desea eliminar: ")
    os.system("cls")
    if tituloBuscado in tituloVideo:
        pos=tituloVideo.index(tituloBuscado)
        print("*****************************************")
        print("             CodeLanguagueES             ")
        print("*****************************************")
        print("          ELIMINACIÓN DE VIDEO           ")
        print("*****************************************")
        print(" Usted está a punto de eliminar el video ")
        print("seleccionado. Por favor, brinde la razón")
        print(" de la eliminación de este recurso de la ")
        print("               plataforma.               ")
        motivoCambioVideo.append(input("Motivo: "))
        os.system("cls")
        print("*****************************************")
        print("                  AVISO                  ")
        print("*****************************************")
        print("La eliminación de un recurso es una acción")
        print("que no puede deshacerse luego de su ejecución")
        print(" Esta acción eliminará el video de forma ")
        print("permanente y no se podrá acceder a el nuevamente.")
        print("*****************************************")
        print(" ¿Está seguro que desea continuar con la ")
        print("    eliminación permanente del video?    ")
        valEliminacion=input("Digite S o N para continuar: ")
        os.system("cls")
        if valEliminacion.upper() == "S":
            tituloVideo.pop(pos)
            nombreAutorVideo.pop(pos)
            categoriaVideo.pop(pos)
            descripcionVideo.pop(pos)
            lenguajeProgVideo.pop(pos)
            linkVideo.pop(pos)
            nombreColabVideo.pop(pos)
            guardarDatosVideo()
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El video ha sido eliminado con éxito. Dentro")
            print("de los próximos minutos los cambios serán")
            print("    visibles para todos los usuarios.    ")
            print("*****************************************")
        elif valEliminacion.upper() == "N":
            print("Proceso cancelado.")
            return
