'''
Autor: André Guido.
'''
import os
# Declaración de campos/parámetros y listas a utilizar en los ficheros.
campos = ["nombreLibro.txt", "nombreAutorLibro.txt", "numEdicion.txt", "lenguajeProgLibro.txt", "descripcionLibro.txt", "linkLibro.txt", "nombreColabLibro.txt","motivoCambioLibro.txt"]
if all(os.path.exists(c) for c in campos):
    with open(campos[0], "r") as f: nombreLibro=f.read().splitlines()
    with open(campos[1], "r") as f: nombreAutorLibro=f.read().splitlines()
    with open(campos[2], "r") as f: numEdicion=f.read().splitlines()
    with open(campos[3], "r") as f: lenguajeProgLibro=f.read().splitlines()
    with open(campos[4], "r") as f: descripcionLibro=f.read().splitlines()
    with open(campos[5], "r") as f: linkLibro=f.read().splitlines()
    with open(campos[6], "r") as f: nombreColabLibro=f.read().splitlines()
    with open(campos[7], "r") as f: motivoCambioLibro=f.read().splitlines()
else:
    nombreLibro=[]
    nombreAutorLibro=[]
    numEdicion=[]
    lenguajeProgLibro=[]
    descripcionLibro=[]
    linkLibro=[]
    nombreColabLibro=[]
    motivoCambioLibro=[]

#Función para guardar los datos del libro en un ficheros.
def guardarDatosLibro():
    with open(campos[0], "w") as f: f.write("\n".join(nombreLibro))
    with open(campos[1], "w") as f: f.write("\n".join(nombreAutorLibro))
    with open(campos[2], "w") as f: f.write("\n".join(numEdicion))
    with open(campos[3], "w") as f: f.write("\n".join(lenguajeProgLibro))
    with open(campos[4], "w") as f: f.write("\n".join(descripcionLibro))
    with open(campos[5], "w") as f: f.write("\n".join(linkLibro))
    with open(campos[6], "w") as f: f.write("\n".join(nombreColabLibro))
    with open(campos[7], "w") as f: f.write("\n".join(motivoCambioLibro))

#Función para agregar/registrar los datos de un libro.
def registrarLibro():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("         FICHA TÉCNICA DE LIBRO          ")
    print("*****************************************")
    print(" Estimado usuario, muchas gracias por su ")
    print("interés en ampliar los recursos literarios")
    print(" referentes a códigos de programación en ")
    print("CodeLanguageEs. Amablemente le solicitamos")
    print("que rellene la siguiente ficha técnica del")
    print("libro que desea registrar en la plataforma.")
    print("*****************************************")
    while True:
        if len(nombreLibro) < 100:
            nombreLibro.append(input("Título del libro: "))
            nombreAutorLibro.append(input("Autor: "))
            numEdicion.append(input("# de Edición: "))
            lenguajeProgLibro.append(input("Lenguaje de programación: "))
            descripcionLibro.append(input("Breve descripción del libro: "))
            linkLibro.append(input("Enlace de acceso al libro: "))
            nombreColabLibro.append(input("Usuario que sube el archivo: "))
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("Usted está a punto de subir un libro con ")
            print("        los siguientes parámetros.       ")
            print("*****************************************")
            print(f"Título del libro: {nombreLibro}")
            print(f"Autor: {nombreAutorLibro}")
            print(f"# de Edición: {numEdicion}")
            print(f"Lenguaje de programación: {lenguajeProgLibro}")
            print(f"Descripción del libro: {descripcionLibro}")
            print(f"Enlace de acceso al libro: {linkLibro}")
            print(f"Usuario que sube el archivo: {nombreColabLibro}")
            print("*****************************************")
            valRespuesta=input("Por favor, ingrese S/N para confirmar su acción: ")
            if valRespuesta.upper() == "S":
                guardarDatosLibro()
                os.system("cls")
                print("Los datos han sido guardados con éxito.")
                break
            elif valRespuesta.upper() == "N":
                os.system("cls")
                print("El proceso ha sido cancelado.")
                break
            else: 
                print("Opción no válida.")
                break

#Función para modificar los parámetros de un libro.
def modificarLibro():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("                 LIBROS                  ")
    print("*****************************************")
    print("Lista de libros: ")
    for i in nombreLibro:
        print(f"{i}\n")
    print("*****************************************") 
    nombreBuscado=input("Ingrese el nombre del libro que desea modificar: ")
    os.system("cls")
    if nombreBuscado in nombreLibro:
        pos=nombreLibro.index(nombreBuscado)
        print("*****************************************")
        print("             CodeLanguagueES             ")
        print("*****************************************")
        print("   MODIFICACIÓN DE PARÁMETROS DE LIBRO   ")
        print("*****************************************")
        print("Por favor, indique el parámetro del libro")
        print("          que desea modificar.           ")
        print("*****************************************")
        print("1- Título del libro.")
        print("2- Autor.")
        print("3- # de Edición.")
        print("4- Lenguaje de programación.")
        print("5- Descripción del libro.")
        print("6- Enlace de acceso al libro")
        print("7- Colaborador.")
        print("8- Cancelar.")
        print("*****************************************")
        valOpcionMod=int(input("Opción: "))
        os.system("cls")
        # Modificación del título del libro.
        if valOpcionMod==1:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Libro: {nombreLibro}          ")
            print("*****************************************")
            print(" Por favor, escriba el nuevo título del  ")
            print("   libro y el motivo de cambio de este   ")
            print("               parámetro.                ")
            print("*****************************************")
            nombreLibro[pos]=input("Nuevo nombre: ")
            motivoCambioLibro.append(input("Motivo: "))
            guardarDatosLibro()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El título del libro ha sido cambiado con ")
            print("éxito. Dentro de los próximos minutos los")
            print("  cambios serán visibles para todos los  ")
            print("                usuarios.                ")
            print("*****************************************")
        
        # Modificación del nombre del autor del libro.
        elif valOpcionMod==2:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Libro: {nombreLibro}          ")
            print("*****************************************")
            print("Por favor, escriba el nuevo autor del libro")
            print("y el motivo de cambio de este parámetro.")
            print("*****************************************")
            nombreAutorLibro[pos]=input("Nuevo autor: ")
            motivoCambioLibro.append(input("Motivo: "))
            guardarDatosLibro()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El nombre del autor ha sido cambiado con ")
            print("éxito. Dentro de los próximos minutos los")
            print("  cambios serán visibles para todos los  ")
            print("                usuarios.                ")
            print("*****************************************")
        
        # Modificación del número de edición del libro.
        elif valOpcionMod==3:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Libro: {nombreLibro}          ")
            print("*****************************************")
            print("Por favor, escriba el nuevo número de edición")
            print(" del libro y el motivo de cambio de este ")
            print("               parámetro.                ")
            print("*****************************************")
            numEdicion[pos]=input("Nuevo # de Edición: ")
            motivoCambioLibro.append(input("Motivo: "))
            guardarDatosLibro()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El número de edición ha sido cambiado con")
            print("éxito. Dentro de los próximos minutos los")
            print("  cambios serán visibles para todos los  ")
            print("                usuarios.                ")
            print("*****************************************")
        
        #Modificaión del lenguaje de programación al que pertenece el libro.
        elif valOpcionMod==4:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Libro: {nombreLibro}          ")
            print("*****************************************")
            print(" Por favor, escriba el nuevo lenguaje de ")
            print("  programación del libro y el motivo de  ")
            print("        cambio de este parámetro.        ")
            print("*****************************************")
            lenguajeProgLibro[pos]=input("Nuevo lenguaje de programación: ")
            motivoCambioLibro.append(input("Motivo: "))
            guardarDatosLibro()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El lenguaje de programación al que pertenecía")
            print("el libro ha sido cambiado con éxito. Dentro")
            print("de los próximos minutos los cambios serán")
            print("    visibles para todos los usuarios.    ")
            print("*****************************************")
        
        #Modificación de la descripción del libro.
        elif valOpcionMod==5:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Libro: {nombreLibro}          ")
            print("*****************************************")
            print("Por favor, escriba la nueva descripción del")
            print("libro y el motivo de cambio de este parámetro")
            print("*****************************************")
            descripcionLibro[pos]=input("Nueva descripción: ")
            motivoCambioLibro.append(input("Motivo: "))
            guardarDatosLibro()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("La descripción del libro ha sido cambiada")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")
        
        #Modificación del enlace de acceso al libro.
        elif valOpcionMod==6:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Libro: {nombreLibro}          ")
            print("*****************************************")
            print("Por favor, escriba el nuevo link de acceso")
            print(" al libro y el motivo de cambio de este  ")
            print("               parámetro.                ")
            print("*****************************************")
            linkLibro[pos]=input("Nuevo link de acceso: ")
            motivoCambioLibro.append(input("Motivo: "))
            guardarDatosLibro()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El link de acceso al libro ha sido cambiado")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")

        #Modificación del nombre del colaborador que subió el libro.
        elif valOpcionMod==7:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"          Libro: {nombreLibro}          ")
            print("*****************************************")
            print("  Por favor, escriba el nuevo nombre del ")
            print("colaborador y el motivo de cambio de este")
            print("               parámetro.                ")
            print("*****************************************")
            nombreColabLibro[pos]=input("Nuevo nombre de colaborador: ")
            motivoCambioLibro.append(input("Motivo: "))
            guardarDatosLibro()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El nombre del colaboradorha sido cambiado")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")
    
    elif valOpcionMod==8:
        print("Proceso cancelado.")
        return

#Función para eliminar un libro del fichero.
def eliminarLibro():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("                 LIBROS                  ")
    print("*****************************************")
    print("Lista de libros: ")
    for i in nombreLibro:
        print(f"{i}\n")
    print("*****************************************") 
    nombreBuscado=input("Ingrese el nombre del libro que desea eliminar: ")
    os.system("cls")
    if nombreBuscado in nombreLibro:
        pos=nombreLibro.index(nombreBuscado)
        print("*****************************************")
        print("             CodeLanguagueES             ")
        print("*****************************************")
        print("          ELIMINACIÓN DE LIBRO           ")
        print("*****************************************")
        print(" Usted está a punto de eliminar el libro ")
        print("seleccionado. Por favor, brinde la razón")
        print(" de la eliminación de este recurso de la ")
        print("               plataforma.               ")
        motivoCambioLibro.append(input("Motivo: "))
        os.system("cls")
        print("*****************************************")
        print("                  AVISO                  ")
        print("*****************************************")
        print("La eliminación de un recurso es una acción")
        print("que no puede deshacerse luego de su ejecución")
        print(" Esta acción eliminará el libro de forma ")
        print("permanente y no se podrá acceder a el nuevamente.")
        print("*****************************************")
        print(" ¿Está seguro que desea continuar con la ")
        print("    eliminación permanente del libro?    ")
        valEliminacion=input("Digite S o N para continuar: ")
        os.system("cls")
        if valEliminacion.upper() == "S":
            nombreLibro.pop(pos)
            nombreAutorLibro.pop(pos)
            numEdicion.pop(pos)
            lenguajeProgLibro.pop(pos)
            descripcionLibro.pop(pos)
            linkLibro.pop(pos)
            nombreColabLibro.pop(pos)
            guardarDatosLibro()
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El libro ha sido eliminado con éxito. Dentro")
            print("de los próximos minutos los cambios serán")
            print("    visibles para todos los usuarios.    ")
            print("*****************************************")
        elif valEliminacion.upper() == "N":
            print("Proceso cancelado.")
            return

