'''
Autor: André Guido.
'''
import os
# Declaración de campos/parámetros y listas a utilizar en los ficheros.
campos = ["tituloSitio.txt", "autorSitio.txt", "lenguajeProgSitio.txt", "descripcionSitio.txt", "fechaPubliSitio.txt", "linkSitio.txt", "nombreColabSitio.txt","motivoCambioVideo.txt"]
if all(os.path.exists(c) for c in campos):
    with open(campos[0], "r") as f: tituloSitio=f.read().splitlines()
    with open(campos[1], "r") as f: autorSitio=f.read().splitlines()
    with open(campos[2], "r") as f: lenguajeProgSitio=f.read().splitlines()
    with open(campos[3], "r") as f: descripcionSitio=f.read().splitlines()
    with open(campos[4], "r") as f: fechaPubliSitio=f.read().splitlines()
    with open(campos[5], "r") as f: linkSitio=f.read().splitlines()
    with open(campos[6], "r") as f: nombreColabSitio=f.read().splitlines()
    with open(campos[7], "r") as f: motivoCambioSitio=f.read().splitlines()
else:
    tituloSitio=[]
    autorSitio=[]
    lenguajeProgSitio=[]
    descripcionSitio=[]
    fechaPubliSitio=[]
    linkSitio=[]
    nombreColabSitio=[]
    motivoCambioSitio=[]

#Función para guardar los datos del sitio web en un ficheros.
def guardarDatosSitioWeb():
    with open(campos[0], "w") as f: f.write("\n".join(tituloSitio))
    with open(campos[1], "w") as f: f.write("\n".join(autorSitio))
    with open(campos[2], "w") as f: f.write("\n".join(lenguajeProgSitio))
    with open(campos[3], "w") as f: f.write("\n".join(descripcionSitio))
    with open(campos[4], "w") as f: f.write("\n".join(fechaPubliSitio))
    with open(campos[5], "w") as f: f.write("\n".join(linkSitio))
    with open(campos[6], "w") as f: f.write("\n".join(nombreColabSitio))
    with open(campos[7], "w") as f: f.write("\n".join(motivoCambioSitio))

#Función para agregar/registrar los datos de un sitio web.
def registrarSitioWeb():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("       FICHA TÉCNICA DE SITIO WEB        ")
    print("*****************************************")
    print(" Estimado usuario, muchas gracias por su ")
    print("   interés en ampliar los recursos web   ")
    print(" referentes a códigos de programación en ")
    print("CodeLanguageEs. Amablemente le solicitamos")
    print("que rellene la siguiente ficha técnica del")
    print("sitio web que desea registrar en la plataforma.")
    print("*****************************************")
    while True:
        if len(tituloSitio) < 100:
            tituloSitio.append(input("Título del sitio web: "))
            autorSitio.append(input("Autor: "))
            lenguajeProgSitio.append(input("Lenguaje de programación: "))
            descripcionSitio.append(input("Breve descripción del sitio web: "))
            fechaPubliSitio.append(input("Fecha de publicación del sitio web: "))
            linkSitio.append(input("Enlace de aceso al sitio web: "))
            nombreColabSitio.append(input("Usuario que sube el archivo: "))
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("Usted está a punto de registrar un sitio ")
            print("    web con los siguientes parámetros.    ")
            print("*****************************************")
            print(f"Título del sitio web: {tituloSitio}")
            print(f"Autor: {autorSitio}")
            print(f"Lenguaje de programación: {lenguajeProgSitio}")
            print(f"Descripción del sitio web: {descripcionSitio}")
            print(f"Fecha de publicación del sitio web: {fechaPubliSitio}")
            print(f"Enlace de acceso al sitio web: {linkSitio}")
            print(f"Usuario que sube el archivo: {nombreColabSitio}")
            print("*****************************************")
            valRespuesta=input("Por favor, ingrese S/N para confirmar su acción: ")
            if valRespuesta.upper() == "S":
                guardarDatosSitioWeb()
                os.system("cls")
                print("Los datos han sido guardados con éxito.")
                break
            elif valRespuesta.upper() == "N":
                os.system("cls")
                print("El proceso ha sido cancelado.")
                break
            else: 
                print("Opción no válida.")
                break

#Función para modificar los parámetros de un sitio web.
def modificarSitioWeb():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("               SITIOS WEB                ")
    print("*****************************************")
    print("Lista de sitios web: ")
    for i in tituloSitio:
        print(f"{i}\n")
    print("*****************************************") 
    sitioBuscado=input("Ingrese el título del sitio web que desea modificar: ")
    os.system("cls")
    if sitioBuscado in tituloSitio:
        pos=tituloSitio.index(sitioBuscado)
        print("*****************************************")
        print("             CodeLanguagueES             ")
        print("*****************************************")
        print(" MODIFICACIÓN DE PARÁMETROS DE SITIO WEB ")
        print("*****************************************")
        print("Por favor, indique el parámetro del sitio")
        print("         web que desea modificar.        ")
        print("*****************************************")
        print("1- Título del sitio web.")
        print("2- Autor.")
        print("3- Lenguaje de programación.")
        print("4- Descripción del sitio web.")
        print("5- Fecha de publicaión del sitio web.")
        print("6- Enlace de acceso al sitio web.")
        print("7- Colaborador.")
        print("8- Cancelar.")
        print("*****************************************")
        valOpcionMod=int(input("Opción: "))
        os.system("cls")
        # Modificación del título del sitio web.
        if valOpcionMod==1:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"        Sitio web: {tituloSitio}        ")
            print("*****************************************")
            print(" Por favor, escriba el nuevo título del  ")
            print(" sitio web y el motivo de cambio de este ")
            print("               parámetro.                ")
            print("*****************************************")
            tituloSitio[pos]=input("Nuevo título: ")
            motivoCambioSitio.append(input("Motivo: "))
            guardarDatosSitioWeb()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print(" El título del sitio web ha sido cambiado")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")
        
        # Modificación del nombre del autor del sitio web.
        elif valOpcionMod==2:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"        Sitio web: {tituloSitio}        ")
            print("*****************************************")
            print("Por favor, escriba el nuevo autor del sitio")
            print("web y el motivo de cambio de este parámetro.")
            print("*****************************************")
            autorSitio[pos]=input("Nuevo autor: ")
            motivoCambioSitio.append(input("Motivo: "))
            guardarDatosSitioWeb()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El nombre del autor ha sido cambiado con ")
            print("éxito. Dentro de los próximos minutos los")
            print("  cambios serán visibles para todos los  ")
            print("                usuarios.                ")
            print("*****************************************")
        
        # Modificación del lenguaje de programación al que pertenece el sitio web.
        elif valOpcionMod==3:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"        Sitio web: {tituloSitio}        ")
            print("*****************************************")
            print(" Por favor, escriba el nuevo lenguaje de ")
            print("programación del sitio web y el motivo de")
            print ("        cambio de este parámetro.       ")
            print("*****************************************")
            lenguajeProgSitio[pos]=input("Nuevo lenguaje de programación: ")
            motivoCambioSitio.append(input("Motivo: "))
            guardarDatosSitioWeb()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El lenguaje de programación al que pertenecía")
            print("el sitio web ha sido cambiado con éxito. ")
            print("Dentro de los próximos minutos los cambios")
            print(" serán visibles para todos los usuarios- ")
            print("*****************************************")
        
        #Modificaión de la descripción del sitio web.
        elif valOpcionMod==4:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"        Sitio web: {tituloSitio}        ")
            print("*****************************************")
            print(" Por favor, escriba la nueva descripción ")
            print("  del sitio web y el motivo de cambio de ")
            print("              este parámetro.            ")
            print("*****************************************")
            descripcionSitio[pos]=input("Nueva descripción: ")
            motivoCambioSitio.append(input("Motivo: "))
            guardarDatosSitioWeb()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("La descripción del sitio web ha sido cambiada")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")
        
        #Modificación de la fecha en que se publicó el sitio web.
        elif valOpcionMod==5:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"        Sitio web: {tituloSitio}        ")
            print("*****************************************")
            print("Por favor, escriba la nueva fecha de publicación")
            print("del sitio web y el motivo de cambio de este")
            print("                parámetro.               ")
            print("*****************************************")
            fechaPubliSitio[pos]=input("Nueva fecha: ")
            motivoCambioSitio.append(input("Motivo: "))
            guardarDatosSitioWeb()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("La fecha de publicación del sitio web ha ")
            print(" sido cambiada con éxtito. Dentro de los ")
            print("próximos minutos los cambios serán visibles")
            print("         para todos los usuarios.        ")
            print("*****************************************")
        
        #Modificación del enlace de acceso al sitio web.
        elif valOpcionMod==6:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"        Sitio web: {tituloSitio}        ")
            print("*****************************************")
            print("Por favor, escriba el nuevo link de acceso")
            print("al sitio web y el motivo de cambio de este")
            print("               parámetro.                ")
            print("*****************************************")
            linkSitio[pos]=input("Nuevo link de acceso: ")
            motivoCambioSitio.append(input("Motivo: "))
            guardarDatosSitioWeb()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print(" El link de acceso al sitio web ha sido  ")
            print("cambiado con éxito. Dentro de los próximos")
            print(" minutos los cambios serán visibles para ")
            print("           todos los usuarios.           ")
            print("*****************************************")

        #Modificación del nombre del colaborador que subió el sitio web.
        elif valOpcionMod==7:
            print("*****************************************")
            print("             CodeLanguagueES             ")
            print("*****************************************")
            print(f"        Sitio web: {tituloSitio}        ")
            print("*****************************************")
            print("  Por favor, escriba el nuevo nombre del ")
            print("colaborador y el motivo de cambio de este")
            print("               parámetro.                ")
            print("*****************************************")
            nombreColabSitio[pos]=input("Nuevo nombre de colaborador: ")
            motivoCambioSitio.append(input("Motivo: "))
            guardarDatosSitioWeb()
            os.system("cls")
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El nombre del colaboradorha sido cambiado")
            print("con éxito. Dentro de los próximos minutos")
            print("los cambios serán visibles para todos los")
            print("                usuarios.                ")
            print("*****************************************")
    
    elif valOpcionMod==8:
        print("Proceso cancelado.")
        return

#Función para eliminar un sitio web del fichero.
def eliminarSitioWeb():
    print("*****************************************")
    print("             CodeLanguagueES             ")
    print("*****************************************")
    print("               SITIOS WEB                ")
    print("*****************************************")
    print("Lista de sitios web: ")
    for i in tituloSitio:
        print(f"{i}\n")
    print("*****************************************") 
    sitioBuscado=input("Ingrese el nombre del sitio web que desea eliminar: ")
    os.system("cls")
    if sitioBuscado in tituloSitio:
        pos=tituloSitio.index(sitioBuscado)
        print("*****************************************")
        print("             CodeLanguagueES             ")
        print("*****************************************")
        print("        ELIMINACIÓN DE SITIO WEB         ")
        print("*****************************************")
        print(" Usted está a punto de eliminar el sitio ")
        print(" web seleccionado. Por favor, brinde la  ")
        print("razón de la eliminación de este recurso de")
        print("             la plataforma.              ")
        motivoCambioSitio.append(input("Motivo: "))
        os.system("cls")
        print("*****************************************")
        print("                  AVISO                  ")
        print("*****************************************")
        print("La eliminación de un recurso es una acción")
        print("que no puede deshacerse luego de su ejecución")
        print(" Esta acción eliminará el sitio web de forma ")
        print("permanente y no se podrá acceder a el nuevamente.")
        print("*****************************************")
        print(" ¿Está seguro que desea continuar con la ")
        print("  eliminación permanente del sitio web?  ")
        valEliminacion=input("Digite S o N para continuar: ")
        os.system("cls")
        if valEliminacion.upper() == "S":
            tituloSitio.pop(pos)
            autorSitio.pop(pos)
            lenguajeProgSitio.pop(pos)
            descripcionSitio.pop(pos)
            fechaPubliSitio.pop(pos)
            linkSitio.pop(pos)
            nombreColabSitio.pop(pos)
            guardarDatosSitioWeb()
            print("*****************************************")
            print("                  AVISO                  ")
            print("*****************************************")
            print("El sitio web ha sido eliminado con éxito.")
            print("Dentro de los próximos minutos los cambios")
            print(" serán visibles para todos los usuarios. ")
            print("*****************************************")
        elif valEliminacion.upper() == "N":
            print("Proceso cancelado.")
            return
